### ISSUE TITLE
UserWarning when saving the model

### ISSUE THREAD

**Issue by yzho0907** [SNUDerek/multiLSTM#4]
python3.5/site-packages/keras/engine/network.py:888: UserWarning: Layer bidirectional_dec was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'bidirectional_enc/while_1/Exit_3:0' shape=(?, 300) dtype=float32>, <tf.Tensor 'bidirectional_enc/while_1/Exit_4:0' shape=(?, 300) dtype=float32>, <tf.Tensor 'bidirectional_enc/while/Exit_3:0' shape=(?, 300) dtype=float32>, <tf.Tensor 'bidirectional_enc/while/Exit_4:0' shape=(?, 300) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included '
any idea how to fix it?

**Comment by SNUDerek** [comment]
it is apparently a keras issue, as discussed here: https://github.com/keras-team/keras/issues/9914

in my code the error seems to be from the `save_all_weights`. however, i am just using the `save_all_weights` to save, well, the weights, not the model architecture. when i recreate model and then load weights from h5 and test, i get the same results as the initial test results. rather than do it in this clumsy way, you can also save with the `to_json` and load the model that way, in which the keywords are saved in the json file (you can visually inspect to confirm). something like:

```
# save architecture with json
with open('model/'+modelname+'.json', 'w') as f:
    f.write(model.to_json())
# save weights
save_load_utils.save_all_weights(model, 'model/'+modelname+'.h5')
# save training history
np.save('model/'+modelname+'_dict.npy', hist_dict)
```

then to load:

```
with open('model/'+modelname+'.json') as f:
    json_string = f.read()
model = model_from_json(json_string, custom_objects={"CRF": CRF, "AttentionWithContext" : AttentionWithContext})
model.load_weights('model/'+modelname+'.h5')
```

i will update to reflect this (save and load with json, also add a post-loading test to demonstrate same results) when i get a chance. thanks.

**Comment by yzho0907** [comment]
@SNUDerek thx
